name: sim
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - root
  - matplotlib
  - numpy
  - scipy
  - pandas
  - pathlib
  - pip
  - yaml
  - tqdm
  - pip:
    - mplhep
    - ninja