#
#	LHCb Verification Framework for the MightyPix
#
#	Task: Configure the inputs for the MightyPix efficiency simulation
#
#	Author: Sigrid Scherl
#
#	Created: January 2023
#

#----------------------------------------------------------------------------------------------------------------------------------------------------------------|
# Parameter           | Input value                 | Explanation                                                                                                |
#----------------------------------------------------------------------------------------------------------------------------------------------------------------|

sim                   : 'comp'                      # sim                   : 'trafo'/'comp'    (Generate new data/compare existing dataset)

data:                                               # data                  : 
  type                : 'scifi'                    #   type                : 'scifi'/'random'  (Use scifi data/use random data)
  version             : '1.1'                       #   version             : 'v1.1'/'v1.0'     (Current version of data and code/old version)

mute                  : True                       # mute                  : False/True        (Print log file with analysis results/mute it)
progress_bars         : False                       # progress_bars         : True/False        (Enable/Disable progress bars when running sim - faulty anyway)

plots:                                              # plots                 :
  save                : False                        #   save                : True/False        (Save plots/don't save plots)
  show                : False                       #   show                : True/False        (Show plots/don't show plots)
  selected            : False                        #   selected            : True/False        (Only selected plots)

chip:                                               # chip                  :                   (Chip specifications)
  name                : 'MightyPix1'                #   name                : String            (MightyPix1 defined, otherwise specifiy dimensions)
  daisy_chain         : False                       #   daisy_chain         : 
  chip_id             : 0                           #   chip_id             : Integer           (ID of daisy chained chip)
  columns             : 29                          #   columns             : Integer           (Number of columns)
  rows                : 320                         #   rows                : Integer           (Number of rows)
  column_width        : 0.165 #mm                   #   column_width        : Float             (Width of column in mm)
  row_width           : 0.055 #mm                   #   column_width        : Float             (Width of column in mm)
  mask_columns        : False                       #   mask_columns        : False/True        (Use all columns/Mask some columns)
  mask_columns_above  : ''                          #   mask_columns_above  : Integer           (Mask columns ABOVE (excluding) the specified number)
  mask_columns_below  : ''                          #   mask_columns_below  : Integer           (Mask columns BELOW (excluding) the specified number)
  mask_rows           : False                       #   mask_rows           : False/True        (Use all rows/Mask some rows)
  mask_rows_above     : ''                          #   mask_rows_above     : Integer           (Mask rows ABOVE (excluding) the specified number)
  mask_rows_below     : ''                          #   mask_rows_below     : Integer           (Mask rows BELOW (excluding) the specified number)
 

rates:                                              # rates                 :                   (Specify the hit rate in MHz/cm^2 when using random data)
  first             : 1                             #   first               : Integer           (Starting value, lowest rate)
  last              : 40                            #   last                : Integer           (Finishing value, highest rate)
  use_list          : True                          #   use_list            : False/True        (Use first+last values (see above)/use values specified in list (see below))
  list              : [31]                          #   list                : Multiple Integers (Specify specific numbers to use)

sensors:                                            # sensors               :                   (Specify ID of sensor positions)
  first             : 0                             #   first               : Integer           (Starting value, lowest sensor ID of range)
  last              : 2963                          #   last                : Integer           (Finishing value, highest sensor ID of range)
  use_list          : True                          #   use_list            : False/True        (Use first+last values (see above)/use values specified in list (see below))
  list              : [739]                         #   list                : Multiple Integers (Specify specific numbers to use)

events:
  list              : [500]

extra               : ['']      # Add any string to end of file names - mostly used for 'newfsm'

layers:
  first             : 1
  last              : 1
  use_list          : True
  list              : [1]
  mode              : 'appended'

quadrants:
  first             : 1
  last              : 1
  use_list          : True
  list              : [1]
  mode              : 'overlapped'

repetitions         : [''] # depreciated

orientation         : 'original'

position            : 'bottom_left'

tot:
  fixed             : [2] #us
  mev_to_us         : 0 # set 0 as conversion factor to use fixed tot value

secondaries         : [False] # this is actually spillover

clusters:
  generate          : [False]
  percentage        : 0.05 #%

fsm_clk             : '40MHz'

tof:
  percentage        : 100
  bins              : 350
  x_lim             : True
  x_min             : 25.5
  x_max             : 32.5

# Directories (Should not change)
directories:
  data:
    raw             : '../data/raw_data/'
    raw_sensor      : '../data/raw_data/sensors/'
    input           : '../data/input_data/'
    output          : '../data/output_data/'
    log             : '../data/log_files/'
    efficiencies    : '../data/efficiencies/'
    rates           : '../data/rates/'
  plots:
    root_histos     : '../plots/root_data_histograms/'
    root_plots      : '../plots/root_data_plots/'
    rate_vs_eff     : '../plots/hit_rate_vs_efficiency/'

# What's the original data file? (Should not change)
files:
  raw_data:
    root            : 'MagUp_bs2phiphi_violaine_energytime_oscar_files_1p5e34.root_Sorted.root_Sensors.root'
    csv             : 'MagUp_bs2phiphi_violaine_energytime_oscar_files_1p5e34_Sorted_Sensors.csv'
    selected        : 'MagUp_bs2phiphi_violaine_energytime_oscar_files_1p5e34_Sorted_Sensors_Selected.csv'
    name            : 'MagUp_bs2phiphi_violaine_energytime_oscar_files_1p5e34_Sorted'
    sensor_list     : 'MagUp_bs2phiphi_violaine_energytime_oscar_files_1p5e34_Sorted_Sensors_List.csv'
  efficiencies:
    empty           : 'efficiencies_empty.csv'
